# Datasource
spring:
  datasource:
    url: jdbc:mysql://mysql-docker-container:3306/testdb?useSSL=false
    driverClassName: com.mysql.cj.jdbc.Driver
    username: sa
    password: p4ssword
  jpa:
    hibernate:
      ## Hibernate ddl auto (create, create-drop, validate, update)
      ddl-auto:create
